### ISSUE TITLE
Bugs in TeukolskyPointParticleMode and TeukolskyRadial

### ISSUE THREAD

**Issue by Patrick-Bourg** [BlackHolePerturbationToolkit/Teukolsky#27]
The TeukolskyPointParticleMode encounters infinite expressions not only for static modes (which is a known issue),
but also m > 0 modes (tested for s=+- 2).
Second, there seems to be a few bugs surrounding TeukolskyRadial: errors/warnings when using numerical integration. infinities when using default method, and Lists mismatch during internal computations.
I have attached a minimal working example that re-produces these errors.

I have been using Mathematica 13.0 (Linux version) with the latest versions of KerrGeodesics and Teukolsky (from the github master branches).
[test.zip](https://github.com/BlackHolePerturbationToolkit/Teukolsky/files/9660086/test.zip)

**Comment by barrywardell** [comment]
Short answer: this is all down to using too low precision. When you set ```r0=10.0`10M;``` you are specifying 10 digit working precision, which is lower than even machine precision. A simple fix is to just remove the "`10" and work at machine precision.

Slightly longer answer: TeukolskyRadial uses different methods depending on whether it is working at machine precision (in which case it uses numerical integration) or arbitrary precision (in which case it uses MST). The MST method in general often needs to have a relatively high working precision in order to produce robust answers, so I would only recommend setting the precision to something other than machine precision if you want more accurate results and are willing to set the precision quite high, 32 digits or higher typically.

**Comment by Patrick-Bourg** [comment]
I see. Thank you for this!
