### ISSUE TITLE
General orbits are still not supported

### ISSUE THREAD

**Issue by zenyanbo** [BlackHolePerturbationToolkit/Teukolsky#46]
Hello, I am very curious as to why general orbits are not supported. Is it because the source term of the Teukolsky equation is difficult to construct?

**Comment by nielsw2** [comment]
Hi, since version 1.0 generic bound orbits have been supported for s={0, +/- 1, +/- 2}. Were you thinking of different orbits? In principle it is not too difficult to extend to plunging and hyperbolic orbits *for a given frequency mode* but summing over the modes becomes much more challenging as the spectrum becomes continuous (rather than discreet as it is for the bound orbit case).

**Comment by zenyanbo** [comment]
Sorry, I saw on the BHPT website that only circular orbits are supported. I checked the commit and then tested the general orbits, and indeed they are supported. I will close this issue.

**Comment by zenyanbo** [comment]
> Hi, since version 1.0 generic bound orbits have been supported for s={0, +/- 1, +/- 2}. Were you thinking of different orbits? In principle it is not too difficult to extend to plunging and hyperbolic orbits _for a given frequency mode_ but summing over the modes becomes much more challenging as the spectrum becomes continuous (rather than discreet as it is for the bound orbit case).

Sorry, I saw on the BHPT website that only circular orbits are supported. I checked the commit and then tested the general orbits, and indeed they are supported. I will close this issue.

**Comment by barrywardell** [comment]
We should update the website. I thought I had done this already but I can see the Teukolsky page still refers to circular orbits.

**Comment by nielsw2** [comment]
I have updated the website to say the package now supports generic orbits.
