### ISSUE TITLE
Loss of accuracy for TeukolskyPointParticleMode

### ISSUE THREAD

**Issue by srd24** [BlackHolePerturbationToolkit/Teukolsky#48]
I am trying to use the BHPT to recreate results from the classic Warburton & Barack 2011 paper on scalar self-force for eccentric orbits in the frequency domain, using extended homogeneous solutions. I encounter a loss of accuracy for particular lmn modes at larger |n|. As an example:
```
orbit = KerrGeoOrbit[0, 10., 0.2, 1];
TeukolskyPointParticleMode[0, 6, 6, -9, 0, orbit];
```
gives the warning 
```
NIntegrate failed to converge to prescribed accuracy after 9 \
iterated refinements in Teukolsky`ConvolveSource`Private`qr in the \
region {{0.,3.14159}}. NIntegrate obtained 142.068 +26.5427\ I and \
0.001574650519576554` for the integral and error estimates.
```

This looks like a relative error of 10^(-5), which is likely too large for successful regularisation. (N.B. the angular frequency for this mode is 0.00965...).

I have tried using extended precision, but then I get a different error message. The example:
```
orbit = KerrGeoOrbit[0, 10.`32, 0.2`32, 1]; 
TeukolskyPointParticleMode[0, 3, 3, -10, 0, orbit];
```
gives the error message:
```
TeukolskyRadialFunction::dmval: Radius 8.33333333333333333333333333333333333333`29.522966490402755 lies outside the computational domain.
NIntegrate::wprec: Value of option WorkingPrecision -> \[Infinity] is not a positive machine-sized real or integer.
```

Is there a workaround? For example, are there any internal parameters/options I can set to improve the accuracy of the integral over the source in the libration region?

I am using Teukolsky-1.0.3 and KerrGeodesics-0.9.0.

**Comment by barrywardell** [comment]
The fix for this has been included in a new version 1.0.4 release.

**Comment by srd24** [comment]
Hi Barry,

Thanks for making the fix, much appreciated!

With the new version, and extended precision, I still get the warning from
NIntegrate, but now the error estimate is substantially smaller (and thus I
expect regularisation to work). Is this the expected behaviour that you
find?

Best wishes,

Sam

**Comment by barrywardell** [comment]
Yes, there is still a warning in this case. NIntegrate is used to compute the integral over the libration region in order to determine the variation-of-parameters weighting coefficients. The warning is saying that the integration did not produce as accurate an answer as we might have expected. For a given working precision, it will aim for a result accurate to (working precision)/2. In this particular case with 32 digits of working precision the integral appears to reach a precision of $~3*10^{-16}$ which is only slightly larger than the target of $1*10^{-16}$ so it's not an issue to be concerned about.
